# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/top1.xdc

# Block Designs: bd/MCU_mem/MCU_mem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_mem || ORIG_REF_NAME==MCU_mem} -quiet] -quiet

# IP: bd/MCU_mem/ip/MCU_mem_dist_mem_gen_0_1/MCU_mem_dist_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MCU_mem_dist_mem_gen_0_1 || ORIG_REF_NAME==MCU_mem_dist_mem_gen_0_1} -quiet] -quiet

# Block Designs: bd/Multiply/Multiply.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Multiply || ORIG_REF_NAME==Multiply} -quiet] -quiet

# IP: bd/Multiply/ip/Multiply_mult_gen_1_0/Multiply_mult_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Multiply_mult_gen_1_0 || ORIG_REF_NAME==Multiply_mult_gen_1_0} -quiet] -quiet

# Block Designs: bd/ram/ram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram || ORIG_REF_NAME==ram} -quiet] -quiet

# IP: bd/ram/ip/ram_dist_mem_gen_1_0/ram_dist_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_dist_mem_gen_1_0 || ORIG_REF_NAME==ram_dist_mem_gen_1_0} -quiet] -quiet

# XDC: bd/MCU_mem/MCU_mem_ooc.xdc

# XDC: bd/Multiply/Multiply_ooc.xdc

# XDC: bd/ram/ram_ooc.xdc
