# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/84546/Desktop/CPU/CPU.cache/wt [current_project]
set_property parent.project_path C:/Users/84546/Desktop/CPU/CPU.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/84546/Desktop/CPU/CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/84546/Desktop/CPU/mem.coe
add_files C:/Users/84546/Desktop/CPU/mem2.coe
add_files C:/Users/84546/Desktop/CPU/task2.coe
add_files C:/Users/84546/Desktop/CPU/task3.coe
add_files C:/Users/84546/Desktop/CPU/task1.coe
add_files C:/Users/84546/Desktop/CPU/mem1.coe
read_verilog -library xil_defaultlib {
  C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/new/top_design.v
  C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/new/ALU.v
  C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/new/ALU_flag_generator.v
  C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/new/CPU.v
  C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/new/MCU.v
  C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/MCU_mem/hdl/MCU_mem_wrapper.v
  C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/Multiply/hdl/Multiply_wrapper.v
  C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/ram/hdl/ram_wrapper.v
}
add_files C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/MCU_mem/MCU_mem.bd
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/MCU_mem/ip/MCU_mem_dist_mem_gen_0_1/MCU_mem_dist_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/MCU_mem/MCU_mem_ooc.xdc]

add_files C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/Multiply/Multiply.bd
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/Multiply/ip/Multiply_mult_gen_1_0/Multiply_mult_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/Multiply/Multiply_ooc.xdc]

add_files C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/ram/ram.bd
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/ram/ip/ram_dist_mem_gen_1_0/ram_dist_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/bd/ram/ram_ooc.xdc]

read_ip -quiet C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/top1.xdc
set_property used_in_implementation false [get_files C:/Users/84546/Desktop/CPU/CPU.srcs/sources_1/top1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_design -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_design.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_design_utilization_synth.rpt -pb top_design_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
